import { z } from "zod";

export const ModelAnswerSchema = z.object({
  provider: z
    .enum(["openai", "anthropic", "gemini"])
    .describe("The provider of the model that generated the answer."),
  answer: z
    .string()
    .max(1000)
    .describe("The answer generated by the model, limited to 1000 characters."),
  latency: z
    .number()
    .describe("The time taken to generate the answer, in milliseconds."),
  success: z
    .boolean()
    .describe("Whether the model successfully generated an answer."),
  error: z
    .string()
    .optional()
    .describe(
      "An optional error message if the model failed to generate an answer.",
    ),
});

export type ModelAnswer = z.infer<typeof ModelAnswerSchema>;

export const JudgeResultSchema = z.object({
  winner: z
    .enum(["openai", "anthropic", "gemini", "tie"])
    .describe(
      "The provider of the model that won the comparison, or 'tie' if there was no clear winner.",
    ),
  reason: z
    .string()
    .max(100)
    .describe(
      "A brief explanation of why the winner was chosen, limited to 100 characters.",
    ),
  finalAnswer: z
    .string()
    .max(1000)
    .describe("The final answer after judging, limited to 1000 characters."),
});

export type JudgeResult = z.infer<typeof JudgeResultSchema>;
