import { z } from "zod";

export const ModelAnswerSchema = z.object({
  provider: z
    .enum(["openai", "anthropic", "gemini"])
    .describe("The provider of the model that generated the answer."),
  answer: z
    .string()
    .max(1000)
    .describe("The answer generated by the model, limited to 1000 characters."),
  latency: z
    .number()
    .describe("The time taken to generate the answer, in milliseconds."),
  success: z
    .boolean()
    .describe("Whether the model successfully generated an answer."),
  error: z
    .string()
    .optional()
    .describe(
      "An optional error message if the model failed to generate an answer.",
    ),
});

export type ModelAnswer = z.infer<typeof ModelAnswerSchema>;

export const JudgeResultSchema = z.object({
  finalAnswer: z
    .string()
    .max(1000)
    .describe("The final answer after judging, limited to 1000 characters."),
  tokens: z.object({
    input: z.number().describe("The number of input tokens used."),
    output: z.number().describe("The number of output tokens used."),
  }),
});

export type JudgeResult = z.infer<typeof JudgeResultSchema>;

export const userQuerySchema = z.object({
  query: z
    .string()
    .max(1000)
    .describe("The user's query, limited to 1000 characters."),
});

export type UserQuery = z.infer<typeof userQuerySchema>;
